name = "serpapi-middleware"
main = "serpApi_worker.js"
compatibility_date = "2024-01-01"

# KV Namespace Binding
# During the 'Deploy to Cloudflare Workers' flow, Cloudflare will ask you to bind a KV namespace to 'REVIEWS_KV'.
[[kv_namespaces]]
binding = "REVIEWS_KV"
id = "04d6aa2c433040eb97b928bda50fdf8c"
